name: ovx_style
description: OVX Style app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #general
  localize_and_translate: ^4.1.1
  image_picker: ^0.8.4+4
  country_code_picker: ^2.0.2
  csc_picker: ^0.2.6
  flutter_colorpicker: ^1.0.2
  video_player: ^2.2.9
  currency_picker: ^2.0.7
  flutter_email_sender: ^5.1.0

  #location and maps
  google_maps_flutter: ^2.1.0
  location: ^4.3.0
  geocoding: ^2.0.2

  #user id generator
  min_id: ^1.1.0

  #animation
  page_transition: ^2.0.4
  flutter_easyloading: ^3.0.0
  dotted_decoration: ^2.0.0
  shimmer_image: ^0.0.2
  shimmer: ^2.0.0
  flutter_svg: ^1.0.0
  scroll_snap_list: ^0.8.4

  #state management
  flutter_bloc: ^7.3.1
  equatable: ^2.0.3

  #shared pref
  shared_preferences: ^2.0.8

  #firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  cloud_functions: ^3.2.6
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0

  #numbers on icon
  badges: ^2.0.2

  #payment
  go_sell_sdk_flutter: ^2.1.1

  #voice_recorder
  flutter_sound: ^9.1.7
  path_provider: ^2.0.9
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400